---
title: "Goal Programming"
author: "Harika"
date: "11/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Given Information:
 y1+ and y1-, respectively, as the amount over (if any) and the amount under (if any) the employment level goal.
 y2+ and y2- in the same way for the goal regarding earnings next year. 
 x1, x2, and x3 as the production rates of Products 1, 2, and 3, respectively. 

P in terms of x1,x2,x3 is P = 20x1 + 15x2 + 25x3.
/*Objective Function 

max: 20x1 + 15x2 + 25x3 - 6y1m -6y1p - 3y2m;

/*Constraints

6x1 + 4x2 + 5x3 - y1p + y1m = 50;
8x1 + 7x2 + 5x3 - y2p + y2m = 75;



```{r}
library(lpSolveAPI)
gp <- read.lp("GOAL.lp")
gp
solve(gp)
get.objective(gp)
get.variables(gp)
```




```{r}
library(lpSolveAPI)
gp1 <- read.lp("goal1.lp")
gp1

solve(gp1)
get.objective(gp1)
get.constraints(gp1)
get.variables(gp1)
```


first stage
```{r}
library(lpSolveAPI)
gp2 <- read.lp("goal_firststage.lp")
gp2

solve(gp2)
get.objective(gp2)
get.constraints(gp2)
get.variables(gp2)
```


second stage 
```{r}
library(lpSolveAPI)
gp3 <- read.lp("goal _secondstage.lp")
gp3

solve(gp3)
get.objective(gp3)
get.constraints(gp3)
get.variables(gp3)
```

